jobs:
- deployment: Deploy
  continueOnError: true
  environment: $(Environment)
  strategy:
    runOnce:
      deploy:
        steps:
      
        # Checkout shared steps
        - checkout: 'tfpipeline-shared'
          displayName: 'Checkout shared Pipeline steps'
          path: 's/pipeline/Shared/'

        # Run common steps
        - template: ./Steps/common.yml@tfpipeline-shared

        # Run steps
        - template: ./Steps/apply.yml@tfpipeline-shared