jobs:
- job: Delay
  pool: Server
  steps:
  
  # Introduce delay to allow service replication
  - task: Delay@1
    displayName: 'Delay for $(DelayMinutes) minutes'
    inputs:
      delayForMinutes: $(DelayMinutes)