jobs:
- job: ReEvaluate
  displayName: 'Evaluate Plan'
  dependsOn: Plan
  condition: and(eq(dependencies.Plan.result,'Succeeded'), eq(dependencies.Plan.outputs['Variable.ShouldRun'], 'true'))
  continueOnError: false
  steps:
  
  # Checkout shared steps
  - checkout: 'tfpipeline-shared'
    displayName: 'Checkout shared Pipeline steps'
    path: 's/pipeline/Shared/'

  # Run common steps
  - template: ./Steps/common.yml@tfpipeline-shared

  # Run Plan Evaluation
  - template: ./Steps/reevaluate.yml@tfpipeline-shared