jobs:
- job: Import
  displayName: 'Validate Workspace'
  steps:
  
  # Checkout shared steps
  - checkout: 'tfpipeline-shared'
    displayName: 'Checkout shared Pipeline steps'
    path: 's/pipeline/Shared/'

  # Run common steps
  - template: ./Steps/common.yml@tfpipeline-shared

  # Run steps
  - template: ./Steps/validate.yml@tfpipeline-shared