jobs:
- job: New
  displayName: 'Create Workspace'
  dependsOn: Import
  condition: eq(dependencies.Import.result,'SucceededWithIssues')
  steps:
  
  # Checkout shared steps
  - checkout: 'tfpipeline-shared'
    displayName: 'Checkout shared Pipeline steps'
    path: 's/pipeline/Shared/'

  # Run common steps
  - template: ./Steps/common.yml@tfpipeline-shared

  # Run steps
  - template: ./Steps/workspace.yml@tfpipeline-shared