stages:
- stage: Plan
  condition: or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), startswith(variables['Build.SourceBranch'], 'refs/heads/release/'), eq(variables['Build.Reason'], 'Manual'))
  pool:
    vmImage: 'ubuntu-latest'
  #dependsOn: Integration
  jobs:
  
  # Validate Jobs
  - template: ../Jobs/validate.yml

  # Workspace Job
  - template: ../Jobs/workspace.yml

  # Plan Jobs
  - template: ../Jobs/plan.yml

  # Plan Evaluation Job
  - template: ../Jobs/evaluate.yml