stages:
- stage: ReApply
  pool:
    vmImage: 'ubuntu-latest'
  dependsOn: RePlan
  condition: and(not(failed()), not(canceled()), eq(dependencies.RePlan.outputs['ReEvaluate.Variable.ShouldRun'], 'true'))
  jobs:
  
  # ReApply Jobs
  - template: ../Jobs/reapply.yml